# Generated by Django 5.0 on 2023-12-11 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='auth',
            field=models.ImageField(upload_to='users/auths/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='degree',
            field=models.ImageField(upload_to='users/degrees/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id_card',
            field=models.ImageField(upload_to='users/profiles/'),
        ),
    ]
