# Generated by Django 5.0 on 2023-12-16 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_code_user_is_confirmed_alter_user_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift',
            name='asr',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='shift',
            name='shab',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='shift',
            name='sobh',
            field=models.BooleanField(null=True),
        ),
    ]
