# Generated by Django 5.0 on 2023-12-17 08:20

import django.db.models.deletion
import django_jalali.db.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_shift_asr_alter_shift_shab_alter_shift_sobh'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='string_date',
            field=models.CharField(default=1, max_length=11),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shift',
            name='asr',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='shift',
            name='shab',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='shift',
            name='sobh',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.CreateModel(
            name='ControlShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('user_change_time', models.IntegerField(default=0)),
                ('limit', models.IntegerField(default=3)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RequestEdit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', django_jalali.db.models.jDateField()),
                ('string_date', models.CharField(max_length=11)),
                ('new_sobh', models.BooleanField(default=False, null=True)),
                ('new_asr', models.BooleanField(default=False, null=True)),
                ('new_shab', models.BooleanField(default=False, null=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('request_date', django_jalali.db.models.jDateField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
