# Generated by Django 5.0 on 2023-12-16 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_shift_string_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift',
            name='asr',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='shift',
            name='shab',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='shift',
            name='sobh',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
