# Generated by Django 5.0 on 2023-12-16 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_controlshift'),
    ]

    operations = [
        migrations.AddField(
            model_name='controlshift',
            name='limit',
            field=models.IntegerField(default=3),
        ),
    ]
